import os
import re
import json
import glob
import io
import argparse
from datetime import datetime
import pandas as pd
import numpy as np
import fitparse

import base64

# Color Palettes for sessions
POWER_SHADES = ['#00b0ff', '#00e5ff', '#0091ea', '#82b1ff', '#2979ff', '#00b8d4', '#00e5ff', '#00838f']
HR_SHADES = ['#ff5252', '#ff1744', '#d50000', '#ff8a80', '#ff3d00', '#dd2c00', '#ff5252', '#c62828']
CORE_TEMP_SHADES = ['#ffab40', '#ff9100', '#ff6d00', '#ffd180', '#ff9100', '#e65100', '#ff8f00', '#f57c00']
LACTATE_SHADES = ['#69f0ae', '#00e676', '#00c853', '#b9f6ca', '#00e676', '#1b5e20', '#2e7d32', '#4caf50']
GLUCOSE_SHADES = ['#ea80fc', '#d500f9', '#aa00ff', '#f50057', '#d500f9', '#4a148c', '#6a1b9a', '#8e24aa']

def decode_plotly_array(val):
    if isinstance(val, list):
        return val
    elif isinstance(val, dict) and 'bdata' in val:
        dtype_map = {
            'f8': np.float64,
            'f4': np.float32,
            'i8': np.int64,
            'i4': np.int32,
            'i2': np.int16,
            'i1': np.int8,
            'u8': np.uint64,
            'u4': np.uint32,
            'u2': np.uint16,
            'u1': np.uint8,
        }
        dt_cls = dtype_map.get(val.get('dtype'), np.float64)
        try:
            bdata_str = str(val['bdata'])
            bdata_str += '=' * (-len(bdata_str) % 4)
            raw_bytes = base64.b64decode(bdata_str)
            itemsize = np.dtype(dt_cls).itemsize
            rem = len(raw_bytes) % itemsize
            if rem != 0:
                raw_bytes = raw_bytes[:-rem]
            if not raw_bytes:
                return []
            arr = np.frombuffer(raw_bytes, dtype=dt_cls)
            return [None if np.isnan(v) else float(v) for v in arr]
        except Exception:
            return []
    return []

def parse_single_session_html(html_source):
    """
    Parses a single-session HTML report (generated by generate_html_report).
    html_source can be a file path (str), HTML string content (str), or bytes object.
    Returns (date_str, session_dict).
    """
    if isinstance(html_source, bytes):
        html_content = html_source.decode('utf-8', errors='ignore')
    elif isinstance(html_source, str) and os.path.exists(html_source):
        with open(html_source, 'r', encoding='utf-8', errors='ignore') as f:
            html_content = f.read()
    elif isinstance(html_source, str):
        html_content = html_source
    else:
        return None, {}

    session = {
        'startTime': None,
        'power_30s': [],
        'hr_30s': [],
        'temp_10s': [],
        'lactate': [],
        'glucose': [],
        'stats': {}
    }
    
    # 1. Parse Metadata (Start Time, Date)
    st_match = re.search(r'活動開始時間.*?:?\s*([\d\-:\s]+)', html_content)
    if st_match:
        st_str = st_match.group(1).strip()
        session['startTime'] = st_str
        date_match = re.search(r'(\d{4}-\d{2}-\d{2})', st_str)
        date_str = date_match.group(1) if date_match else st_str[:10]
    else:
        date_str = "Unknown Date"
        
    # 2. Parse KPI Cards for stats
    kpi_matches = re.findall(r'<div class="kpi-card">\s*<div class="kpi-label">(.*?)</div>\s*<div class="kpi-value"[^>]*>(.*?)</div>', html_content, re.DOTALL)
    for label, val in kpi_matches:
        label_clean = re.sub(r'<[^>]+>', '', label).strip()
        val_clean = re.sub(r'<[^>]+>', '', val).strip()
        if "時長" in label_clean:
            session['stats']['duration'] = val_clean
        elif "功率" in label_clean:
            parts = val_clean.replace("W", "").split("/")
            if len(parts) == 2:
                try:
                    session['stats']['avg_power'] = int(parts[0].strip())
                    session['stats']['max_power'] = int(parts[1].strip())
                except ValueError:
                    pass
        elif "心率" in label_clean:
            parts = val_clean.replace("bpm", "").split("/")
            if len(parts) == 2:
                try:
                    session['stats']['avg_hr'] = int(parts[0].strip())
                    session['stats']['max_hr'] = int(parts[1].strip())
                except ValueError:
                    pass
        elif "溫度" in label_clean:
            session['stats']['max_temp'] = val_clean.replace("°C", "").strip()

    # 3. Parse Summary Table with Regex
    table_match = re.search(r'<table[^>]*summary-table[^"]*"[^>]*>(.*?)</table>', html_content, re.DOTALL)
    if table_match:
        table_html = table_match.group(1)
        headers = [re.sub(r'<[^>]+>', '', th).strip() for th in re.findall(r'<th[^>]*>(.*?)</th>', table_html, re.DOTALL)]
        tr_matches = re.findall(r'<tr[^>]*>(.*?)</tr>', table_html, re.DOTALL)
        for tr in tr_matches:
            tds = [re.sub(r'<[^>]+>', '', td).strip() for td in re.findall(r'<td[^>]*>(.*?)</td>', tr, re.DOTALL)]
            if tds and len(tds) == len(headers):
                row_dict = dict(zip(headers, tds))
                t_val = row_dict.get('量測時間 (分)')
                lac_val = row_dict.get('乳酸值 (mmol/L)')
                glu_val = row_dict.get('血糖值 (mg/dL)')
                src_val = row_dict.get('量測點來源', '自訂時間')
                pw_val = row_dict.get('對應功率 (W)')
                hr_val = row_dict.get('對應心率 (BPM)')
                tp_val = row_dict.get('對應核心溫度 (°C)')
                
                if t_val:
                    try:
                        t_float = float(t_val)
                        if lac_val and lac_val != "-":
                            item = {'x': t_float, 'y': float(lac_val), 'source': src_val}
                            if pw_val and pw_val != "-": item['power'] = int(float(pw_val))
                            if hr_val and hr_val != "-": item['hr'] = int(float(hr_val))
                            if tp_val and tp_val != "-": item['temp'] = float(tp_val)
                            session['lactate'].append(item)
                        if glu_val and glu_val != "-":
                            item = {'x': t_float, 'y': int(float(glu_val)), 'source': src_val}
                            if pw_val and pw_val != "-": item['power'] = int(float(pw_val))
                            if hr_val and hr_val != "-": item['hr'] = int(float(hr_val))
                            if tp_val and tp_val != "-": item['temp'] = float(tp_val)
                            session['glucose'].append(item)
                    except ValueError:
                        pass

    # 4. Parse Plotly Traces for timeseries (Power 30s, HR 30s, Core Temp 10s)
    match = re.search(r'Plotly\.newPlot\(\s*"[^"]+"\s*,\s*(\[.*?\])\s*,\s*(\{.*?\})\s*[\),]', html_content, re.DOTALL)
    if match:
        traces = json.loads(match.group(1))
        for t in traces:
            name = str(t.get('name', ''))
            x_arr = decode_plotly_array(t.get('x'))
            y_arr = decode_plotly_array(t.get('y'))
            
            if "30s" in name or "功率" in name:
                if not session['power_30s'] and len(x_arr) == len(y_arr):
                    step = max(1, len(x_arr) // 500)
                    for i in range(0, len(x_arr), step):
                        if y_arr[i] is not None:
                            session['power_30s'].append({'x': round(x_arr[i], 2), 'y': round(y_arr[i], 1)})
            elif "心率" in name:
                if not session['hr_30s'] and len(x_arr) == len(y_arr):
                    step = max(1, len(x_arr) // 500)
                    for i in range(0, len(x_arr), step):
                        if y_arr[i] is not None:
                            session['hr_30s'].append({'x': round(x_arr[i], 2), 'y': round(y_arr[i], 1)})
            elif "核心溫度" in name or "溫度" in name:
                if not session['temp_10s'] and len(x_arr) == len(y_arr):
                    step = max(1, len(x_arr) // 500)
                    for i in range(0, len(x_arr), step):
                        if y_arr[i] is not None:
                            session['temp_10s'].append({'x': round(x_arr[i], 2), 'y': round(y_arr[i], 2)})
            elif "乳酸" in name and not session['lactate']:
                for xi, yi in zip(x_arr, y_arr):
                    if xi is not None and yi is not None:
                        session['lactate'].append({'x': round(xi, 2), 'y': round(yi, 2), 'source': '報告圖表'})
            elif "血糖" in name and not session['glucose']:
                for xi, yi in zip(x_arr, y_arr):
                    if xi is not None and yi is not None:
                        session['glucose'].append({'x': round(xi, 2), 'y': round(yi, 1), 'source': '報告圖表'})

    # Calculate max lactate / max glucose in stats if not present
    if session['lactate']:
        max_lac = max(pt['y'] for pt in session['lactate'] if pt.get('y') is not None)
        session['stats']['max_lactate'] = f"{max_lac:.1f} mmol/L"
    if session['glucose']:
        max_glu = max(pt['y'] for pt in session['glucose'] if pt.get('y') is not None)
        session['stats']['max_glucose'] = f"{int(max_glu)} mg/dL"

    return date_str, session

def load_historical_data(html_path):
    """
    Extracts rawLactateData from an existing integrated HTML report.
    This acts as a backup seed if the original FIT files are missing.
    """
    if not os.path.exists(html_path):
        return {}
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            content = f.read()
        match = re.search(r'const rawLactateData\s*=\s*(\{.*?\});', content, re.DOTALL)
        if match:
            return json.loads(match.group(1))
    except Exception as e:
        print(f"[Warning] Failed to parse historical HTML data from {html_path}: {e}")
    return {}

def parse_fit_file(fit_source):
    """
    Parses a FIT file and returns a cleaned timeseries DataFrame and start time.
    fit_source can be a filepath (str) or a bytes object.
    """
    if isinstance(fit_source, bytes):
        fit_file = fitparse.FitFile(io.BytesIO(fit_source))
    else:
        fit_file = fitparse.FitFile(fit_source)
        
    records = []
    for record in fit_file.get_messages('record'):
        vals = {field.name: field.value for field in record.fields}
        records.append(vals)
        
    df = pd.DataFrame(records)
    if df.empty or 'timestamp' not in df.columns:
        return pd.DataFrame(), None
        
    df = df.sort_values(by='timestamp').reset_index(drop=True)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    if df['timestamp'].dt.tz is not None:
        df['timestamp'] = df['timestamp'].dt.tz_localize(None)
    df['timestamp'] = df['timestamp'] + pd.Timedelta(hours=8)
    start_time = df['timestamp'].iloc[0]
    
    # Calculate elapsed minutes from start
    df['elapsed_minutes'] = (df['timestamp'] - start_time).dt.total_seconds() / 60.0
    
    # Parse core temperature
    if 'core_temperature' in df.columns:
        df['core_temp'] = df['core_temperature'].apply(lambda x: x / 100.0 if (pd.notna(x) and x > 1000) else x)
    elif 'unknown_139' in df.columns:
        df['core_temp'] = df['unknown_139'].apply(lambda x: x / 100.0 if (pd.notna(x) and x > 1000) else x)
    else:
        df['core_temp'] = np.nan
        
    # Ensure standard columns are present
    for col in ['heart_rate', 'power']:
        if col not in df.columns:
            df[col] = np.nan
            
    df_clean = df[['timestamp', 'elapsed_minutes', 'heart_rate', 'power', 'core_temp']].copy()
    return df_clean, start_time

def smooth_and_downsample(df, downsample_seconds=10):
    """
    Applies 30s rolling average smoothing on Power and HR, then downsamples the FIT series.
    """
    if df.empty:
        return pd.DataFrame()
        
    df = df.copy()
    if 'power' in df.columns and df['power'].notna().any():
        df['power_smoothed'] = df['power'].rolling(window=30, min_periods=1).mean()
    else:
        df['power_smoothed'] = np.nan
        
    if 'heart_rate' in df.columns and df['heart_rate'].notna().any():
        df['hr_smoothed'] = df['heart_rate'].rolling(window=30, min_periods=1).mean()
    else:
        df['hr_smoothed'] = np.nan
        
    # Downsampling to standard interval
    step_minutes = downsample_seconds / 60.0
    df['grid_time'] = (df['elapsed_minutes'] / step_minutes).round() * step_minutes
    
    df_downsampled = df.groupby('grid_time').agg({
        'power_smoothed': lambda x: x.mean() if x.notna().any() else np.nan,
        'hr_smoothed': lambda x: x.mean() if x.notna().any() else np.nan,
        'core_temp': lambda x: x.mean() if x.notna().any() else np.nan
    }).reset_index()
    
    df_downsampled = df_downsampled.rename(columns={'grid_time': 'elapsed_minutes'})
    # Convert NaNs to None for JSON compliance
    df_downsampled = df_downsampled.replace({np.nan: None})
    return df_downsampled

def find_column_name(df, patterns):
    cols = df.columns
    for col in cols:
        col_lower = str(col).strip().lower()
        for pat in patterns:
            if col_lower == pat.lower():
                return col
    for col in cols:
        col_lower = str(col).strip().lower()
        for pat in patterns:
            if pat.lower() in col_lower:
                return col
    return None

def parse_lactate_file(file_source):
    """
    Parses a lactate sheet (Excel or CSV).
    Returns DataFrame with ['elapsed_minutes', 'lactate', 'glucose', 'source'] columns.
    """
    if isinstance(file_source, bytes):
        try:
            df = pd.read_excel(io.BytesIO(file_source))
        except Exception:
            try:
                df = pd.read_csv(io.BytesIO(file_source))
            except Exception:
                return pd.DataFrame()
    else:
        ext = os.path.splitext(file_source)[1].lower()
        try:
            if ext in ['.xlsx', '.xls']:
                df = pd.read_excel(file_source)
            else:
                df = pd.read_csv(file_source)
        except Exception:
            return pd.DataFrame()
            
    time_col = find_column_name(df, ["相對時間", "時間", "time", "elapsed", "duration", "min", "分鐘", "分"])
    lac_col = find_column_name(df, ["乳酸", "lac", "mmol"])
    glu_col = find_column_name(df, ["血糖", "glucose", "glu", "mg/dl", "mg"])
    src_col = find_column_name(df, ["來源", "source", "量測點來源"])
    
    if time_col is None:
        return pd.DataFrame()
        
    res_df = pd.DataFrame()
    res_df['elapsed_minutes'] = pd.to_numeric(df[time_col], errors='coerce')
    
    if lac_col is not None:
        res_df['lactate'] = pd.to_numeric(df[lac_col], errors='coerce')
    else:
        res_df['lactate'] = np.nan
        
    if glu_col is not None:
        res_df['glucose'] = pd.to_numeric(df[glu_col], errors='coerce')
    else:
        res_df['glucose'] = np.nan
        
    if src_col is not None:
        res_df['source'] = df[src_col].fillna("自訂時間").astype(str)
    else:
        res_df['source'] = "自訂時間"
        
    res_df = res_df.dropna(subset=['elapsed_minutes']).sort_values(by='elapsed_minutes').reset_index(drop=True)
    res_df = res_df.replace({np.nan: None})
    return res_df

def compute_session_stats(df_fit_down, df_lac):
    stats = {
        'max_power': '-',
        'avg_power': '-',
        'max_hr': '-',
        'avg_hr': '-',
        'max_temp': '-',
        'max_lactate': '-',
        'max_glucose': '-'
    }
    
    if not df_fit_down.empty:
        # Convert values back to float (ignoring None/NaN) for computation
        pw = [p for p in df_fit_down['power_smoothed'] if p is not None and pd.notna(p)]
        if pw:
            stats['max_power'] = int(max(pw))
            stats['avg_power'] = int(sum(pw)/len(pw))
            
        hr = [h for h in df_fit_down['hr_smoothed'] if h is not None and pd.notna(h)]
        if hr:
            stats['max_hr'] = int(max(hr))
            stats['avg_hr'] = int(sum(hr)/len(hr))
            
        temp = [t for t in df_fit_down['core_temp'] if t is not None and pd.notna(t)]
        if temp:
            stats['max_temp'] = f"{max(temp):.2f}"
            
    if not df_lac.empty:
        lac = [l for l in df_lac['lactate'] if l is not None and pd.notna(l)]
        if lac:
            stats['max_lactate'] = f"{max(lac):.1f} mmol/L"
            
        glu = [g for g in df_lac['glucose'] if g is not None and pd.notna(g)]
        if glu:
            stats['max_glucose'] = f"{int(max(glu))} mg/dL"
            
    return stats

def build_integrated_html(raw_data_dict, theme='dark'):
    is_dark = (theme == 'dark')
    bg_color = "#0f172a" if is_dark else "#f8fafc"
    text_color = "#f8fafc" if is_dark else "#000000"
    card_bg = "rgba(30, 41, 59, 0.7)" if is_dark else "#ffffff"
    axis_color = "'rgba(255, 255, 255, 0.5)'" if is_dark else "'#000000'"
    tick_color = "'#94a3b8'" if is_dark else "'#000000'"
    title_color = "'#cbd5e1'" if is_dark else "'#000000'"
    legend_color = "'#e2e8f0'" if is_dark else "'#000000'"
    """
    Generates a beautiful Chart.js-based integrated HTML report using the raw data dictionary.
    """
    dates = sorted(list(raw_data_dict.keys()))
    
    # 1. Generate KPI Cards HTML
    kpi_cards_html = ""
    for date in dates:
        session = raw_data_dict[date]
        stats = session.get('stats', {})
        start_time_str = session.get('startTime', date)
        
        # Check if glucose stats exist
        glucose_box_html = ""
        max_glu = stats.get('max_glucose', '-')
        if max_glu != '-':
            glucose_box_html = f"""
                    <div class="metric-box">
                        <span class="metric-title" style="color: #d500f9;">🩸 最大血糖</span>
                        <span class="metric-value">{max_glu}</span>
                    </div>
            """
            
        kpi_cards_html += f"""
            <div class="kpi-card">
                <div class="kpi-header">
                    <span class="kpi-date">📅 {date}</span>
                    <span class="kpi-time">{start_time_str}</span>
                </div>
                <div class="kpi-metrics">
                    <div class="metric-box">
                        <span class="metric-title" style="color: var(--color-power);">⚡ 功率 (Avg/Max)</span>
                        <span class="metric-value">{stats.get('avg_power', '-')} / {stats.get('max_power', '-')} W</span>
                    </div>
                    <div class="metric-box">
                        <span class="metric-title" style="color: var(--color-hr);">❤️ 心率 (Avg/Max)</span>
                        <span class="metric-value">{stats.get('avg_hr', '-')} / {stats.get('max_hr', '-')} bpm</span>
                    </div>
                    <div class="metric-box">
                        <span class="metric-title" style="color: var(--color-temp);">🔥 最大核心溫度</span>
                        <span class="metric-value">{stats.get('max_temp', '-') if stats.get('max_temp', '-') != '-' else '-'} °C</span>
                    </div>
                    <div class="metric-box">
                        <span class="metric-title" style="color: var(--color-lactate);">🩸 最大乳酸</span>
                        <span class="metric-value">{stats.get('max_lactate', '-')}</span>
                    </div>
                    {glucose_box_html}
                </div>
            </div>
        """
        
    # 2. Generate Date Toggles HTML
    date_toggles_html = ""
    for date in dates:
        date_toggles_html += f'<button class="btn active" data-date="{date}">📅 {date}</button>\n'
        
    # 3. Dynamic metric toggles (Check if glucose is present anywhere)
    has_glucose_anywhere = False
    for session in raw_data_dict.values():
        if 'glucose' in session and session['glucose'] and any(pt.get('y') is not None for pt in session['glucose']):
            has_glucose_anywhere = True
            break
            
    glucose_toggle_html = ""
    if has_glucose_anywhere:
        glucose_toggle_html = '<button class="btn active" data-metric="glucose">🩸 血糖 (mg/dL)</button>'
        
    # 4. Generate JavaScript Color Objects
    color_power_js = {}
    color_hr_js = {}
    color_temp_js = {}
    color_lactate_js = {}
    color_glucose_js = {}
    
    for idx, date in enumerate(dates):
        color_power_js[date] = POWER_SHADES[idx % len(POWER_SHADES)]
        color_hr_js[date] = HR_SHADES[idx % len(HR_SHADES)]
        color_temp_js[date] = CORE_TEMP_SHADES[idx % len(CORE_TEMP_SHADES)]
        color_lactate_js[date] = LACTATE_SHADES[idx % len(LACTATE_SHADES)]
        color_glucose_js[date] = GLUCOSE_SHADES[idx % len(GLUCOSE_SHADES)]
        
    color_config_js = {
        'power': color_power_js,
        'hr': color_hr_js,
        'coreTemp': color_temp_js,
        'lactate': color_lactate_js,
        'glucose': color_glucose_js
    }

    # HTML content template
    html_template = f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>乳酸與生理指標整合多期分析儀表板</title>
    <!-- Outfit & Inter Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <!-- Chart.js CDN & Zoom Plugin -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@2.0.1/dist/chartjs-plugin-zoom.min.js"></script>
    <style>
        :root {{
            --bg-color: {bg_color};
            --card-bg: {card_bg};
            --card-border: {'rgba(255, 255, 255, 0.06)' if is_dark else 'rgba(0, 0, 0, 0.1)'};
            --text-primary: {text_color};
            --text-secondary: {tick_color.strip("'")};
            
            --color-power: #00e5ff;
            --color-power-glow: rgba(0, 229, 255, 0.15);
            --color-hr: #ff1744;
            --color-hr-glow: rgba(255, 23, 68, 0.15);
            --color-temp: #ff9100;
            --color-temp-glow: rgba(255, 145, 0, 0.15);
            --color-lactate: #00e676;
            --color-lactate-glow: rgba(0, 230, 118, 0.15);
            --color-glucose: #d500f9;
            --color-glucose-glow: rgba(213, 0, 249, 0.15);
        }}

        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }}

        body {{
            background-color: var(--bg-color);
            background-image: 
                radial-gradient(circle at 20% 30%, rgba(0, 229, 255, 0.03) 0%, transparent 40%),
                radial-gradient(circle at 80% 70%, rgba(255, 23, 68, 0.03) 0%, transparent 40%);
            color: var(--text-primary);
            font-family: 'Outfit', 'Inter', system-ui, -apple-system, sans-serif;
            min-height: 100vh;
            padding: 40px 20px;
            overflow-x: hidden;
        }}

        .container {{
            max-width: 1400px;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            gap: 30px;
        }}

        /* Header */
        header {{
            display: flex;
            flex-direction: column;
            gap: 8px;
            border-bottom: 1px solid rgba(255, 255, 255, 0.05);
            padding-bottom: 24px;
        }}

        .title-wrapper {{
            display: flex;
            align-items: center;
            gap: 15px;
        }}

        .logo-icon {{
            font-size: 2.2rem;
            background: linear-gradient(135deg, var(--color-lactate), var(--color-power));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            filter: drop-shadow(0 0 10px rgba(0, 230, 118, 0.3));
        }}

        h1 {{
            font-size: 2.5rem;
            font-weight: 800;
            background: linear-gradient(135deg, #ffffff 30%, #cbd5e1 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.5px;
        }}

        .subtitle {{
            font-size: 1.1rem;
            color: var(--text-secondary);
            font-weight: 400;
        }}

        /* KPI Grid */
        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(360px, 1fr));
            gap: 20px;
        }}

        .kpi-card {{
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            border-radius: 16px;
            padding: 24px;
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2);
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }}

        .kpi-card::before {{
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 4px;
            background: linear-gradient(90deg, var(--color-power), var(--color-lactate));
            opacity: 0.8;
        }}

        .kpi-card:hover {{
            transform: translateY(-5px);
            border-color: rgba(255, 255, 255, 0.12);
            box-shadow: 0 12px 40px 0 rgba(0, 0, 0, 0.3);
        }}

        .kpi-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }}

        .kpi-date {{
            font-size: 1.3rem;
            font-weight: 700;
            letter-spacing: 0.5px;
        }}

        .kpi-time {{
            font-size: 0.85rem;
            color: var(--text-secondary);
            background: rgba(255, 255, 255, 0.05);
            padding: 4px 10px;
            border-radius: 20px;
            border: 1px solid rgba(255, 255, 255, 0.05);
        }}

        .kpi-metrics {{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
        }}

        .metric-box {{
            background: rgba(255, 255, 255, 0.02);
            border: 1px solid rgba(255, 255, 255, 0.03);
            border-radius: 10px;
            padding: 12px;
            display: flex;
            flex-direction: column;
            gap: 4px;
        }}

        .metric-title {{
            font-size: 0.8rem;
            color: var(--text-secondary);
            text-transform: uppercase;
            letter-spacing: 0.5px;
            font-weight: 600;
        }}

        .metric-value {{
            font-size: 1.25rem;
            font-weight: 700;
        }}

        /* Controls Section */
        .controls-section {{
            background: rgba(13, 20, 35, 0.3);
            border: 1px solid var(--card-border);
            border-radius: 16px;
            padding: 24px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }}

        .control-group-title {{
            font-size: 0.95rem;
            font-weight: 600;
            color: var(--text-secondary);
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 8px;
        }}

        .control-group-title::after {{
            content: '';
            flex: 1;
            height: 1px;
            background: rgba(255, 255, 255, 0.05);
        }}

        .button-group {{
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
        }}

        .btn {{
            font-family: inherit;
            font-size: 0.95rem;
            font-weight: 600;
            padding: 10px 20px;
            border-radius: 30px;
            border: 1px solid rgba(255, 255, 255, 0.08);
            background: rgba(255, 255, 255, 0.02);
            color: var(--text-secondary);
            cursor: pointer;
            transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
            display: flex;
            align-items: center;
            gap: 8px;
            outline: none;
        }}

        .btn:hover {{
            color: var(--text-primary);
            background: rgba(255, 255, 255, 0.06);
            border-color: rgba(255, 255, 255, 0.15);
        }}

        /* Toggle Active Styles */
        .btn.active[data-date] {{
            background: rgba(255, 255, 255, 0.9);
            color: #020617;
            border-color: #ffffff;
            box-shadow: 0 0 15px rgba(255, 255, 255, 0.15);
        }}

        .btn.active[data-metric="power"] {{
            border-color: var(--color-power);
            color: var(--color-power);
            background: var(--color-power-glow);
            box-shadow: 0 0 15px rgba(0, 229, 255, 0.1);
        }}

        .btn.active[data-metric="hr"] {{
            border-color: var(--color-hr);
            color: var(--color-hr);
            background: var(--color-hr-glow);
            box-shadow: 0 0 15px rgba(255, 23, 68, 0.1);
        }}

        .btn.active[data-metric="coreTemp"] {{
            border-color: var(--color-temp);
            color: var(--color-temp);
            background: var(--color-temp-glow);
            box-shadow: 0 0 15px rgba(255, 145, 0, 0.1);
        }}

        .btn.active[data-metric="lactate"] {{
            border-color: var(--color-lactate);
            color: var(--color-lactate);
            background: var(--color-lactate-glow);
            box-shadow: 0 0 15px rgba(0, 230, 118, 0.1);
        }}
        
        .btn.active[data-metric="glucose"] {{
            border-color: var(--color-glucose);
            color: var(--color-glucose);
            background: var(--color-glucose-glow);
            box-shadow: 0 0 15px rgba(213, 0, 249, 0.1);
        }}

        .btn-utility {{
            font-size: 0.85rem;
            padding: 8px 16px;
            border-radius: 8px;
            background: transparent;
            border: 1px dashed rgba(255, 255, 255, 0.15);
        }}

        #font-scale-select {{
            appearance: none;
            -webkit-appearance: none;
            -moz-appearance: none;
            background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='%2394a3b8' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='6 9 12 15 18 9'></polyline></svg>");
            background-repeat: no-repeat;
            background-position: right 15px center;
            background-size: 16px;
            padding-right: 40px;
        }}

        #font-scale-select:hover {{
            background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='%23f8fafc' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polyline points='6 9 12 15 18 9'></polyline></svg>");
        }}

        /* Chart Section */
        .chart-card {{
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            border-radius: 16px;
            padding: 30px;
            backdrop-filter: blur(12px);
            -webkit-backdrop-filter: blur(12px);
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2);
            position: relative;
        }}

        .chart-wrapper {{
            position: relative;
            width: 100%;
            height: 720px;
        }}

        footer {{
            text-align: center;
            color: var(--text-secondary);
            font-size: 0.9rem;
            padding: 20px 0 40px 0;
            border-top: 1px solid rgba(255, 255, 255, 0.05);
            margin-top: 20px;
        }}

        @media (max-width: 768px) {{
            h1 {{
                font-size: 2rem;
            }}
            .kpi-grid {{
                grid-template-columns: 1fr;
            }}
            .chart-wrapper {{
                height: 480px;
            }}
            body {{
                padding: 20px 10px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <header>
            <div class="title-wrapper">
                <span class="logo-icon">🩸</span>
                <h1>生理指標與乳酸多期整合分析儀表板</h1>
            </div>
            <div class="subtitle">生理數據與乳酸動力學多期對比分析 (功率與心率為 30 秒平均值；滑鼠在圖表上框選可局部放大，按住 Ctrl 拖曳可移動，或使用重設按鈕還原)</div>
        </header>

        <!-- KPI Grid -->
        <div class="kpi-grid">
            {kpi_cards_html}
        </div>

        <!-- Controls Section -->
        <div class="controls-section">
            <div>
                <div class="control-group-title">訓練日期選擇 (Date Toggles)</div>
                <div class="button-group" id="date-buttons">
                    {date_toggles_html}
                    <button class="btn btn-utility" id="select-all-dates">全選</button>
                    <button class="btn btn-utility" id="clear-all-dates">清除</button>
                </div>
            </div>
            <div>
                <div class="control-group-title">生理指標選擇 (Metric Toggles)</div>
                <div class="button-group" id="metric-buttons">
                    <button class="btn active" data-metric="power">⚡ 功率 (30s平均)</button>
                    <button class="btn active" data-metric="hr">❤️ 心率 (30s平均)</button>
                    <button class="btn active" data-metric="coreTemp">🔥 核心溫度 (°C)</button>
                    <button class="btn active" data-metric="lactate">🩸 乳酸 (mmol/L)</button>
                    {glucose_toggle_html}
                    <button class="btn btn-utility" id="select-all-metrics">全選</button>
                    <button class="btn btn-utility" id="clear-all-metrics">清除</button>
                </div>
            </div>
            <div>
                <div class="control-group-title">圖表文字與縮放工具 (Chart Font & Zoom Tools)</div>
                <div class="button-group">
                    <select id="font-scale-select" class="btn">
                        <option value="1" style="background: var(--bg-color); color: var(--text-primary);">1x (標準)</option>
                        <option value="1.25" style="background: var(--bg-color); color: var(--text-primary);">1.25x</option>
                        <option value="1.5" style="background: var(--bg-color); color: var(--text-primary);">1.5x</option>
                        <option value="1.75" style="background: var(--bg-color); color: var(--text-primary);">1.75x</option>
                        <option value="2" style="background: var(--bg-color); color: var(--text-primary);">2x</option>
                    </select>
                    <button class="btn" id="reset-zoom-btn">🔍 重設圖表縮放 (Reset Zoom)</button>
                </div>
            </div>
        </div>

        <!-- Chart Section -->
        <div class="chart-card">
            <div class="chart-wrapper">
                <canvas id="lactateChart"></canvas>
            </div>
        </div>

        <!-- Footer -->
        <footer>
            乳酸動力學整合工具 &copy; {datetime.now().year} | 提供多期生理指標與血糖深度交叉對照功能
        </footer>
    </div>

    <!-- Data Injection -->
    <script>
        const rawLactateData = {json.dumps(raw_data_dict)};
        const hasGlucose = {json.dumps(has_glucose_anywhere)};

        // Active states
        const activeDates = {{}};
        Object.keys(rawLactateData).forEach(date => {{
            activeDates[date] = true;
        }});
        
        const activeMetrics = {{
            'power': true,
            'hr': true,
            'coreTemp': true,
            'lactate': true,
            'glucose': true
        }};

        // Base font sizes for Scaling
        const baseFontSizes = {{
            legend: 12,
            axisTitle: 14,
            axisTicks: 12,
            tooltipTitle: 14,
            tooltipBody: 13
        }};

        // Color definitions for curves (solid, dashed, dotted styles for dates)
        const colors = {json.dumps(color_config_js)};
        const dateList = Object.keys(rawLactateData).sort();
        
        function getDashPattern(date) {{
            const idx = dateList.indexOf(date);
            const patterns = [[], [5, 5], [2, 2], [10, 5], [5, 2, 2, 2]];
            return patterns[idx % patterns.length];
        }}
        
        function getPointStyle(date) {{
            const idx = dateList.indexOf(date);
            const styles = ['rectRot', 'circle', 'triangle', 'rect', 'star'];
            return styles[idx % styles.length];
        }}
        
        function hasValidData(arr) {{
            return arr && arr.some(pt => pt.y !== null && pt.y !== undefined);
        }}

        // Generate Chart.js datasets
        const datasets = [];
        
        Object.keys(rawLactateData).forEach(date => {{
            const session = rawLactateData[date];
            
            // 1. Power (30s Avg)
            if (session.power_30s && session.power_30s.length > 0) {{
                datasets.push({{
                    label: `${{date}} 功率 (30s平均)`,
                    data: session.power_30s,
                    borderColor: colors['power'][date],
                    backgroundColor: colors['power'][date] + '15',
                    yAxisID: 'yPowerHr',
                    metric: 'power',
                    date: date,
                    borderWidth: 2,
                    tension: 0.25,
                    pointRadius: 0,
                    pointHoverRadius: 4,
                    hidden: false,
                    borderDash: getDashPattern(date)
                }});
            }}

            // 2. Heart Rate (30s Avg)
            if (session.hr_30s && session.hr_30s.length > 0) {{
                datasets.push({{
                    label: `${{date}} 心率 (30s平均)`,
                    data: session.hr_30s,
                    borderColor: colors['hr'][date],
                    backgroundColor: colors['hr'][date] + '15',
                    yAxisID: 'yPowerHr',
                    metric: 'hr',
                    date: date,
                    borderWidth: 2,
                    tension: 0.25,
                    pointRadius: 0,
                    pointHoverRadius: 4,
                    hidden: false,
                    borderDash: getDashPattern(date)
                }});
            }}

            // 3. Core Temp
            if (session.temp_10s && session.temp_10s.length > 0 && hasValidData(session.temp_10s)) {{
                datasets.push({{
                    label: `${{date}} 核心溫度 (°C)`,
                    data: session.temp_10s,
                    borderColor: colors['coreTemp'][date],
                    backgroundColor: colors['coreTemp'][date] + '15',
                    yAxisID: 'yCoreTemp',
                    metric: 'coreTemp',
                    date: date,
                    borderWidth: 2,
                    tension: 0.25,
                    pointRadius: 0,
                    pointHoverRadius: 4,
                    hidden: false,
                    borderDash: getDashPattern(date)
                }});
            }}

            // 4. Lactate
            if (session.lactate && session.lactate.length > 0) {{
                datasets.push({{
                    label: `${{date}} 乳酸 (mmol/L)`,
                    data: session.lactate,
                    borderColor: colors['lactate'][date],
                    backgroundColor: colors['lactate'][date] + '33',
                    yAxisID: 'yLactate',
                    metric: 'lactate',
                    date: date,
                    borderWidth: 3,
                    tension: 0.15,
                    pointRadius: 6,
                    pointHoverRadius: 8,
                    pointStyle: getPointStyle(date),
                    hidden: false,
                    borderDash: getDashPattern(date)
                }});
            }}
            
            // 5. Glucose
            if (session.glucose && session.glucose.length > 0 && hasValidData(session.glucose)) {{
                datasets.push({{
                    label: `${{date}} 血糖 (mg/dL)`,
                    data: session.glucose,
                    borderColor: colors['glucose'][date],
                    backgroundColor: colors['glucose'][date] + '33',
                    yAxisID: 'yGlucose',
                    metric: 'glucose',
                    date: date,
                    borderWidth: 3,
                    tension: 0.15,
                    pointRadius: 6,
                    pointHoverRadius: 8,
                    pointStyle: 'circle',
                    hidden: false,
                    borderDash: getDashPattern(date)
                }});
            }}
        }});

        // Setup Chart
        const ctx = document.getElementById('lactateChart').getContext('2d');
        
        // Define axes scales dynamically
        const chartScales = {{
            x: {{
                type: 'linear',
                title: {{
                    display: true,
                    text: '相對時間 (分鐘)',
                    color: {tick_color},
                    font: {{ family: 'Outfit', size: baseFontSizes.axisTitle, weight: 'bold' }}
                }},
                grid: {{
                    drawOnChartArea: false,
                    drawTicks: true,
                    tickLength: 6,
                    tickWidth: 2,
                    lineWidth: 2,
                    color: {axis_color}
                }},
                border: {{
                    display: true,
                    width: 2,
                    color: {axis_color}
                }},
                ticks: {{
                    color: {tick_color},
                    font: {{ family: 'Inter', size: baseFontSizes.axisTicks }}
                }}
            }},
            yPowerHr: {{
                type: 'linear',
                position: 'left',
                title: {{
                    display: true,
                    text: '功率 (W) / 心率 (BPM)',
                    color: {title_color},
                    font: {{ family: 'Outfit', size: baseFontSizes.axisTitle, weight: 'bold' }}
                }},
                grid: {{
                    drawOnChartArea: false,
                    drawTicks: true,
                    tickLength: 6,
                    tickWidth: 2,
                    lineWidth: 2,
                    color: {axis_color}
                }},
                border: {{
                    display: true,
                    width: 2,
                    color: {axis_color}
                }},
                ticks: {{
                    color: {title_color},
                    font: {{ family: 'Inter', size: baseFontSizes.axisTicks }}
                }},
                min: 0,
                suggestedMax: 450
            }},
            yLactate: {{
                type: 'linear',
                position: 'right',
                title: {{
                    display: true,
                    text: '乳酸值 (mmol/L)',
                    color: '#00e676',
                    font: {{ family: 'Outfit', size: baseFontSizes.axisTitle, weight: 'bold' }}
                }},
                grid: {{
                    drawOnChartArea: false,
                    drawTicks: true,
                    tickLength: 6,
                    tickWidth: 2,
                    lineWidth: 2,
                    color: {axis_color}
                }},
                border: {{
                    display: true,
                    width: 2,
                    color: {axis_color}
                }},
                ticks: {{
                    color: '#00e676',
                    font: {{ family: 'Inter', size: baseFontSizes.axisTicks }}
                }},
                min: 0,
                suggestedMax: 30
            }},
            yCoreTemp: {{
                type: 'linear',
                position: 'right',
                title: {{
                    display: true,
                    text: '核心溫度 (°C)',
                    color: '#ff9100',
                    font: {{ family: 'Outfit', size: baseFontSizes.axisTitle, weight: 'bold' }}
                }},
                grid: {{
                    drawOnChartArea: false,
                    drawTicks: true,
                    tickLength: 6,
                    tickWidth: 2,
                    lineWidth: 2,
                    color: {axis_color}
                }},
                border: {{
                    display: true,
                    width: 2,
                    color: {axis_color}
                }},
                ticks: {{
                    color: '#ff9100',
                    font: {{ family: 'Inter', size: baseFontSizes.axisTicks }}
                }},
                min: 36,
                max: 42
            }}
        }};

        // If glucose is present, add the yGlucose axis
        if (hasGlucose) {{
            chartScales.yGlucose = {{
                type: 'linear',
                position: 'right',
                title: {{
                    display: true,
                    text: '血糖值 (mg/dL)',
                    color: '#d500f9',
                    font: {{ family: 'Outfit', size: baseFontSizes.axisTitle, weight: 'bold' }}
                }},
                grid: {{
                    drawOnChartArea: false,
                    drawTicks: true,
                    tickLength: 6,
                    tickWidth: 2,
                    lineWidth: 2,
                    color: {axis_color}
                }},
                border: {{
                    display: true,
                    width: 2,
                    color: {axis_color}
                }},
                ticks: {{
                    color: '#d500f9',
                    font: {{ family: 'Inter', size: baseFontSizes.axisTicks }}
                }},
                min: 50,
                suggestedMax: 200
            }};
        }}

        const lactateChart = new Chart(ctx, {{
            type: 'line',
            data: {{
                datasets: datasets
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                interaction: {{
                    mode: 'index',
                    intersect: false
                }},
                plugins: {{
                    zoom: {{
                        pan: {{
                            enabled: true,
                            mode: 'x',
                            modifierKey: 'ctrl',
                            onPan: function({{chart}}) {{
                                autoScaleYAxes(chart);
                            }}
                        }},
                        zoom: {{
                            drag: {{
                                enabled: true,
                                borderColor: 'rgba(255, 255, 255, 0.25)',
                                borderWidth: 1,
                                backgroundColor: 'rgba(0, 229, 255, 0.08)'
                            }},
                            mode: 'x',
                            onZoom: function({{chart}}) {{
                                autoScaleYAxes(chart);
                            }}
                        }}
                    }},
                    legend: {{
                        display: true,
                        position: 'top',
                        labels: {{
                            color: {legend_color},
                            font: {{
                                family: 'Outfit, sans-serif',
                                size: baseFontSizes.legend
                            }},
                            boxWidth: 20,
                            padding: 15
                        }}
                    }},
                    tooltip: {{
                        backgroundColor: 'rgba(15, 23, 42, 0.9)',
                        titleColor: '#f8fafc',
                        titleFont: {{ family: 'Outfit', size: baseFontSizes.tooltipTitle, weight: 'bold' }},
                        bodyColor: '#cbd5e1',
                        bodyFont: {{ family: 'Inter', size: baseFontSizes.tooltipBody }},
                        borderColor: 'rgba(255, 255, 255, 0.1)',
                        borderWidth: 1,
                        padding: 12,
                        cornerRadius: 8,
                        callbacks: {{
                            title: function(context) {{
                                return `相對時間: ${{context[0].parsed.x.toFixed(2)}} 分 (${{Math.floor(context[0].parsed.x)}}分${{Math.round((context[0].parsed.x % 1) * 60)}}秒)`;
                            }},
                            label: function(context) {{
                                const raw = context.raw;
                                let label = context.dataset.label || '';
                                if (label) {{
                                    label += ': ';
                                }}
                                if (context.parsed.y !== null) {{
                                    label += context.parsed.y;
                                }}
                                if (raw.time) {{
                                    label += ` (${{raw.time}})`;
                                }}
                                if (raw.source) {{
                                    label += ` [${{raw.source}}]`;
                                }}
                                return label;
                            }}
                        }}
                    }}
                }},
                scales: chartScales
            }}
        }});

        // Function to update visibility of datasets
        function updateChartVisibility() {{
            lactateChart.data.datasets.forEach(dataset => {{
                const date = dataset.date;
                const metric = dataset.metric;
                
                const dateActive = activeDates[date];
                const metricActive = activeMetrics[metric];
                
                dataset.hidden = !(dateActive && metricActive);
            }});
            
            autoScaleYAxes(lactateChart);
            lactateChart.update();
        }}

        // Auto scale Y axes based on visible X-axis range
        function autoScaleYAxes(chart) {{
            const xMin = chart.scales.x.min;
            const xMax = chart.scales.x.max;

            const axisRanges = {{
                yPowerHr: {{ min: Infinity, max: -Infinity }},
                yLactate: {{ min: Infinity, max: -Infinity }},
                yCoreTemp: {{ min: Infinity, max: -Infinity }},
                yGlucose: {{ min: Infinity, max: -Infinity }}
            }};

            chart.data.datasets.forEach(dataset => {{
                if (dataset.hidden) return;

                const axisId = dataset.yAxisID;
                if (!axisRanges[axisId]) return;

                const data = dataset.data;
                data.forEach(pt => {{
                    if (pt.x >= xMin && pt.x <= xMax && pt.y !== null && pt.y !== undefined) {{
                        if (pt.y < axisRanges[axisId].min) axisRanges[axisId].min = pt.y;
                        if (pt.y > axisRanges[axisId].max) axisRanges[axisId].max = pt.y;
                    }}
                }});
            }});

            // yPowerHr (Power / HR)
            if (axisRanges.yPowerHr.min !== Infinity) {{
                const minVal = axisRanges.yPowerHr.min;
                const maxVal = axisRanges.yPowerHr.max;
                const pad = (maxVal - minVal) * 0.05 || 10;
                chart.options.scales.yPowerHr.min = Math.max(0, Math.floor(minVal - pad));
                chart.options.scales.yPowerHr.max = Math.ceil(maxVal + pad);
            }} else {{
                chart.options.scales.yPowerHr.min = 0;
                chart.options.scales.yPowerHr.max = 450;
            }}

            // yLactate (Lactate)
            if (axisRanges.yLactate.min !== Infinity) {{
                const minVal = axisRanges.yLactate.min;
                const maxVal = axisRanges.yLactate.max;
                const pad = (maxVal - minVal) * 0.05 || 1;
                chart.options.scales.yLactate.min = Math.max(0, Math.floor(minVal - pad));
                chart.options.scales.yLactate.max = Math.ceil(maxVal + pad);
            }} else {{
                chart.options.scales.yLactate.min = 0;
                chart.options.scales.yLactate.max = 30;
            }}

            // yCoreTemp (Core Temp)
            if (axisRanges.yCoreTemp.min !== Infinity) {{
                const minVal = axisRanges.yCoreTemp.min;
                const maxVal = axisRanges.yCoreTemp.max;
                const pad = (maxVal - minVal) * 0.05 || 0.2;
                chart.options.scales.yCoreTemp.min = Math.max(35, Number((minVal - pad).toFixed(1)));
                chart.options.scales.yCoreTemp.max = Math.min(43, Number((maxVal + pad).toFixed(1)));
            }} else {{
                chart.options.scales.yCoreTemp.min = 36;
                chart.options.scales.yCoreTemp.max = 42;
            }}
            
            // yGlucose (Glucose)
            if (chart.options.scales.yGlucose) {{
                if (axisRanges.yGlucose.min !== Infinity) {{
                    const minVal = axisRanges.yGlucose.min;
                    const maxVal = axisRanges.yGlucose.max;
                    const pad = (maxVal - minVal) * 0.05 || 10;
                    chart.options.scales.yGlucose.min = Math.max(0, Math.floor(minVal - pad));
                    chart.options.scales.yGlucose.max = Math.ceil(maxVal + pad);
                }} else {{
                    chart.options.scales.yGlucose.min = 50;
                    chart.options.scales.yGlucose.max = 200;
                }}
            }}
        }}

        // Reset chart zoom and reset scale bounds to default
        function resetChartZoom() {{
            lactateChart.options.scales.yPowerHr.min = 0;
            lactateChart.options.scales.yPowerHr.suggestedMax = 450;
            if (lactateChart.options.scales.yPowerHr.max !== undefined) {{
                delete lactateChart.options.scales.yPowerHr.max;
            }}

            lactateChart.options.scales.yLactate.min = 0;
            lactateChart.options.scales.yLactate.suggestedMax = 30;
            if (lactateChart.options.scales.yLactate.max !== undefined) {{
                delete lactateChart.options.scales.yLactate.max;
            }}

            lactateChart.options.scales.yCoreTemp.min = 36;
            lactateChart.options.scales.yCoreTemp.max = 42;
            
            if (lactateChart.options.scales.yGlucose) {{
                lactateChart.options.scales.yGlucose.min = 50;
                lactateChart.options.scales.yGlucose.suggestedMax = 200;
                if (lactateChart.options.scales.yGlucose.max !== undefined) {{
                    delete lactateChart.options.scales.yGlucose.max;
                }}
            }}

            lactateChart.resetZoom();
        }}

        // Button Event Listeners
        document.querySelectorAll('[data-date]').forEach(btn => {{
            btn.addEventListener('click', function() {{
                const date = this.getAttribute('data-date');
                activeDates[date] = !activeDates[date];
                this.classList.toggle('active', activeDates[date]);
                updateChartVisibility();
            }});
        }});

        document.querySelectorAll('[data-metric]').forEach(btn => {{
            btn.addEventListener('click', function() {{
                const metric = this.getAttribute('data-metric');
                activeMetrics[metric] = !activeMetrics[metric];
                this.classList.toggle('active', activeMetrics[metric]);
                updateChartVisibility();
            }});
        }});

        // Utility Buttons
        document.getElementById('select-all-dates').addEventListener('click', () => {{
            document.querySelectorAll('[data-date]').forEach(btn => {{
                const date = btn.getAttribute('data-date');
                activeDates[date] = true;
                btn.classList.add('active');
            }});
            updateChartVisibility();
        }});

        document.getElementById('clear-all-dates').addEventListener('click', () => {{
            document.querySelectorAll('[data-date]').forEach(btn => {{
                const date = btn.getAttribute('data-date');
                activeDates[date] = false;
                btn.classList.remove('active');
            }});
            updateChartVisibility();
        }});

        document.getElementById('select-all-metrics').addEventListener('click', () => {{
            document.querySelectorAll('[data-metric]').forEach(btn => {{
                const metric = btn.getAttribute('data-metric');
                activeMetrics[metric] = true;
                btn.classList.add('active');
            }});
            updateChartVisibility();
        }});

        document.getElementById('clear-all-metrics').addEventListener('click', () => {{
            document.querySelectorAll('[data-metric]').forEach(btn => {{
                const metric = btn.getAttribute('data-metric');
                activeMetrics[metric] = false;
                btn.classList.remove('active');
            }});
            updateChartVisibility();
        }});

        // Font Scale Event Listener
        document.getElementById('font-scale-select').addEventListener('change', function() {{
            const scale = parseFloat(this.value);
            
            // Update Legend labels font size
            lactateChart.options.plugins.legend.labels.font.size = baseFontSizes.legend * scale;
            
            // Update Tooltip font sizes
            lactateChart.options.plugins.tooltip.titleFont.size = baseFontSizes.tooltipTitle * scale;
            lactateChart.options.plugins.tooltip.bodyFont.size = baseFontSizes.tooltipBody * scale;
            
            // Update X Scale
            lactateChart.options.scales.x.title.font.size = baseFontSizes.axisTitle * scale;
            lactateChart.options.scales.x.ticks.font.size = baseFontSizes.axisTicks * scale;
            
            // Update Y Scales
            const yScales = ['yPowerHr', 'yLactate', 'yCoreTemp', 'yGlucose'];
            yScales.forEach(axisId => {{
                if (lactateChart.options.scales[axisId]) {{
                    lactateChart.options.scales[axisId].title.font.size = baseFontSizes.axisTitle * scale;
                    lactateChart.options.scales[axisId].ticks.font.size = baseFontSizes.axisTicks * scale;
                }}
            }});
            
            lactateChart.update();
        }});

        // Reset Zoom Event Listener
        document.getElementById('reset-zoom-btn').addEventListener('click', resetChartZoom);

        // Initial visibility update
        updateChartVisibility();
    </script>
</body>
</html>
"""
    return html_template

def process_integration(fit_dir, lac_dir, output_html_path, base_html_path=None):
    """
    Main integration process.
    - Loads base/historical data.
    - Scans for FIT files and matches them with Excel/CSV sheets.
    - Generates new Chart.js HTML report.
    """
    # 1. Load existing historical data
    final_data = {}
    if base_html_path and os.path.exists(base_html_path):
        print(f"Loading historical data from {base_html_path}...")
        final_data = load_historical_data(base_html_path)
        print(f"Loaded {len(final_data)} historical sessions: {list(final_data.keys())}")
        
    # 2. Scan FIT files in fit_dir
    fit_files = glob.glob(os.path.join(fit_dir, "**/*.fit"), recursive=True) + glob.glob(os.path.join(fit_dir, "*.fit"))
    fit_files = list(set(fit_files)) # deduplicate
    
    print(f"Found {len(fit_files)} FIT files in {fit_dir}")
    
    # 3. Scan Lactate files in lac_dir
    lac_files = glob.glob(os.path.join(lac_dir, "*.xlsx")) + glob.glob(os.path.join(lac_dir, "*.csv"))
    print(f"Found {len(lac_files)} Lactate sheets in {lac_dir}")
    
    # Parse each lactate sheet and try to find a matching FIT file
    for lac_file in lac_files:
        basename = os.path.basename(lac_file)
        # Try to extract date pattern (YYYY-MM-DD) from filename
        date_match = re.search(r'(\d{4}-\d{2}-\d{2})', basename)
        if not date_match:
            continue
            
        session_date = date_match.group(1)
        print(f"\nProcessing session date: {session_date}...")
        
        # Parse lactate sheet
        df_lac = parse_lactate_file(lac_file)
        if df_lac.empty:
            print(f"  [Warning] Lactate file empty or invalid: {basename}")
            continue
            
        # Find matching FIT file (by date in filepath or start time)
        matching_fit_path = None
        for fit_path in fit_files:
            # Check if filename contains the date
            if session_date.replace("-", "") in os.path.basename(fit_path) or session_date in fit_path:
                matching_fit_path = fit_path
                break
                
        # If not matched by filename, let's parse the fit file start time to match
        if not matching_fit_path:
            for fit_path in fit_files:
                try:
                    # Quick parse start time
                    fit_file = fitparse.FitFile(fit_path)
                    for message in fit_file.get_messages('record'):
                        first_ts = message.get_value('timestamp')
                        if first_ts:
                            fit_date = first_ts.strftime('%Y-%m-%d')
                            if fit_date == session_date:
                                matching_fit_path = fit_path
                                break
                    if matching_fit_path:
                        break
                except Exception:
                    pass
                    
        df_fit_down = pd.DataFrame()
        start_time_str = session_date
        
        if matching_fit_path:
            print(f"  Found matching FIT file: {os.path.basename(matching_fit_path)}")
            try:
                df_fit, start_time = parse_fit_file(matching_fit_path)
                if not df_fit.empty:
                    df_fit_down = smooth_and_downsample(df_fit, downsample_seconds=10)
                    start_time_str = start_time.strftime('%Y-%m-%d %H:%M:%S')
            except Exception as e:
                print(f"  [Error] Failed to parse matched FIT file: {e}")
        else:
            print(f"  [Info] No matching FIT file found for {session_date}.")
            # If historical data exists for this date, let's keep it!
            if session_date in final_data:
                print(f"  Keeping existing historical FIT data for {session_date}.")
                df_fit_down = pd.DataFrame() # empty so we don't overwrite
                
        # Prepare datasets to inject
        power_30s = []
        hr_30s = []
        temp_10s = []
        
        if not df_fit_down.empty:
            for _, r in df_fit_down.iterrows():
                power_30s.append({'x': r['elapsed_minutes'], 'y': r['power_smoothed']})
                hr_30s.append({'x': r['elapsed_minutes'], 'y': r['hr_smoothed']})
                temp_10s.append({'x': r['elapsed_minutes'], 'y': r['core_temp']})
        elif session_date in final_data:
            # Carry over historical continuous curves
            power_30s = final_data[session_date].get('power_30s', [])
            hr_30s = final_data[session_date].get('hr_30s', [])
            temp_10s = final_data[session_date].get('temp_10s', [])
            start_time_str = final_data[session_date].get('startTime', start_time_str)
            
        # Parse lactate/glucose points
        lactate_points = []
        glucose_points = []
        
        for _, r in df_lac.iterrows():
            t = r['elapsed_minutes']
            # Align with FIT metrics if fit data is available
            aligned_p = None
            aligned_h = None
            aligned_t = None
            
            if not df_fit_down.empty:
                diffs = (df_fit_down['elapsed_minutes'] - t).abs()
                closest_idx = diffs.idxmin()
                closest = df_fit_down.iloc[closest_idx]
                aligned_p = closest['power_smoothed']
                aligned_h = closest['hr_smoothed']
                aligned_t = closest['core_temp']
                
            lac_val = r['lactate']
            glu_val = r['glucose']
            
            if lac_val is not None:
                item = {'x': t, 'y': lac_val, 'source': r['source']}
                if aligned_p is not None: item['power'] = int(aligned_p) if pd.notna(aligned_p) else None
                if aligned_h is not None: item['hr'] = int(aligned_h) if pd.notna(aligned_h) else None
                if aligned_t is not None: item['temp'] = round(aligned_t, 2) if pd.notna(aligned_t) else None
                lactate_points.append(item)
                
            if glu_val is not None:
                item = {'x': t, 'y': glu_val, 'source': r['source']}
                if aligned_p is not None: item['power'] = int(aligned_p) if pd.notna(aligned_p) else None
                if aligned_h is not None: item['hr'] = int(aligned_h) if pd.notna(aligned_h) else None
                if aligned_t is not None: item['temp'] = round(aligned_t, 2) if pd.notna(aligned_t) else None
                glucose_points.append(item)
                
        # If no new FIT data is parsed but we had historical stats, compute stats from new Excel data
        # mixed with whatever FIT data we had.
        # Let's rebuild the temporary dataframes for stats calculation
        df_fit_temp = pd.DataFrame()
        if power_30s:
            df_fit_temp = pd.DataFrame({
                'power_smoothed': [pt['y'] for pt in power_30s],
                'hr_smoothed': [pt['y'] for pt in hr_30s],
                'core_temp': [pt['y'] for pt in temp_10s]
            })
            
        stats = compute_session_stats(df_fit_temp, df_lac)
        
        # Save or update session
        final_data[session_date] = {
            'startTime': start_time_str,
            'power_30s': power_30s,
            'hr_30s': hr_30s,
            'temp_10s': temp_10s,
            'lactate': lactate_points,
            'glucose': glucose_points,
            'stats': stats
        }
        
    if not final_data:
        print("[Error] No session data available to integrate. Exiting.")
        return False
        
    # 4. Generate final HTML contents
    print("\nGenerating final integrated HTML...")
    html_content = build_integrated_html(final_data)
    
    os.makedirs(os.path.dirname(output_html_path), exist_ok=True)
    with open(output_html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
        
    print(f"[Success] Multi-session integrated report generated at: {output_html_path}")
    return True

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Lactate Multi-Session Integration Report Generator")
    parser.add_argument("--fit-dir", default="0521", help="Directory containing .fit files")
    parser.add_argument("--lac-dir", default="TimeLac", help="Directory containing lactate xlsx/csv sheets")
    parser.add_argument("--output", default="LactateReport/LacV5.html", help="Path to write the integrated HTML dashboard")
    parser.add_argument("--base", default="LactateReport/LacV5.html", help="Base integrated HTML to seed historical data")
    
    args = parser.parse_args()
    process_integration(args.fit_dir, args.lac_dir, args.output, args.base)
